### ISSUE TITLE
FFMPEG not cleaning old .ts files with current settings

### ISSUE THREAD

**Issue by francis-chiss** [Roverr/rtsp-stream#13]
Used your project as-is for a couple of hours and ended up with 1 Gb of data lying around. After some extended research, I managed to obtain what I (and I think you) wanted, with the following settings changed in processor.go :

(pasting the patch content did not go well! I have attached it instead!
[processor.go.txt](https://github.com/Roverr/rtsp-stream/files/3000002/processor.go.txt)

)

Successfully made it run with both your Dockerfile on my local system, although I had to add an EXPOSE statement in both to have the ports 8080 and 80 accessible.

Also, I had to add the following line to Dockerfile.management because of a build error (parsel was missing):

(...)
RUN npm install -g parcel-bundler
(...)

Good job!

**Comment by Roverr** [comment]
Thank you for opening this issue!

Yes this is exactly what I was trying to achieve. This is the exact reason why the function that cleans up the streams that are not active anymore also deletes the folder. I tried to fix this a couple of times but did not have any luck with it. So thank you for also fixing this, I'll include these changes in a new release soon.

The management Dockerfile actually has this issue because I have the dependencies installed locally as well. The parcel-bundler is a dev dependency (as it should be), but the image used the `--production` flag during install. Because I copy the whole directory, this did not come out for me unfortunately. That's a mistake and thank you for pointing it out 👏

**Comment by francis-chiss** [comment]
My pleasure!

Your workaround would not have worked for me because I'm transcoding a
security camera, so the feed never ends, and my users might leave the web
page open for a few hours...

Have a nice week!

Francis
