### ISSUE TITLE
RTSP URL as Environment Variable

### ISSUE THREAD

**Issue by hunterlong** [Roverr/rtsp-stream#33]
The RTSP URL should be available to set as a docker environment variable rather than a `HTTP POST`(https://github.com/Roverr/rtsp-stream/blob/master/docs/api/README.md#post-start) to `/start`. 

How can this Docker image be fully automated without another container/command to make the POST. 

Actually... why can't I set within the config yaml file?!    -_-

**Comment by Roverr** [comment]
Hi @hunterlong ,

Well it could be settable yeah why not, no one ever wanted to change it that's why you cannot set it right now.

The main docker image is just providing the backend for your services. This is the best way to provide an easy interface to integrate with, as you can use it from your browser, or you can even use it from other backend services. Having a docker image with the client will never be flexible enough, as most of the time clients will be unique implementations.
There's a really wacky [UI solution](https://github.com/Roverr/rtsp-stream/tree/master/ui/src) you can use that has a docker image [(roverr/rtsp-stream:2-management)](https://github.com/Roverr/rtsp-stream/blob/master/Dockerfile.management). In the future this might get developed into a complete client solution but that's probably down the road. It has to be more or less customisable in terms of layout / branding, flexible around hosting (docker / cdn) and allow for configuration (like where's the backend) after build.
